# Generated by Django 5.0.2 on 2024-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('doctor_name', models.CharField(choices=[('Dr. Sandip Bhirud', 'Dr. Sandip Bhirud (Dentist)10.00AM To 2:00PM'), ('Dr. Kishore Jadhavar', 'Dr. Kishore Jadhavar (Psychiatrist)10.00AM To 2:00PM'), ('Dr. Priya Palimkar', 'Dr. Priya Palimkar (Cardiology)10.00AM To 2:00PM'), ('Dr. Pratik Patil', 'Dr. Pratik Patil (Oncologist)10.00AM To 2:00PM'), ('Dr. Mahesh Sabade', 'Dr. Mahesh Sabade (Ayurveda)10.00AM To 2:00PM'), ('Dr. Atul Patil', 'Dr. Atul Patil (General surgeon)10.00AM To 2:00PM')], max_length=100)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason_for_visit', models.TextField()),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
