# Generated by Django 5.0.2 on 2024-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoints', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
