# Generated by Django 5.0.2 on 2024-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoints', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
            ],
        ),
    ]
